pipeline:
  # restore-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   restore: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules

  install:
    image: node:10.13-alpine
    commands:
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  generate:
    image: node:10.13-alpine
    commands:
      - yarn generate

  push:
    image: node:10.13-alpine
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - yarn push
    when:
      branch: master

  # rebuild-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   rebuild: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   mount:
  #     - ./.yarn-cache
  #     - ./node_modules
  #   when:
  #     branch: master

  # flush-cache:
  #   image: plugins/s3-cache:1
  #   pull: true
  #   secrets: [ aws_access_key_id, aws_secret_access_key ]
  #   root: publici-drone/
  #   flush: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    template: >
      {{#success build.status}}
        published https://apps.publicintegrity.org/women-in-state-politics/
      {{else}}
        failed publishing https://apps.publicintegrity.org/women-in-state-politics/
      {{/success}}
